version: '3'

services:
  nsqlookupd:
    image: nsqio/nsq:lts
    command: /nsqlookupd
    restart: always
    ports:
     - '4160'
     - '4161'
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookup-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - '4150'
      - '4151'
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171"

